# Generated by Django 4.2 on 2023-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                ("product_code", models.CharField(max_length=150)),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
