# Generated by Django 4.1.5 on 2023-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="productdetail",
            name="size",
        ),
        migrations.AddField(
            model_name="productdetail",
            name="sizes",
            field=models.ManyToManyField(related_name="products", to="Product.size"),
        ),
    ]
