# Generated by Django 4.1.5 on 2023-04-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_size_remove_productdetail_size_productdetail_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
