# Generated by Django 4.1.5 on 2023-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_productdetail_remove_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="product_code",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
