# Generated by Django 4.1.5 on 2023-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_alter_productdetail_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="productdetail",
            name="price",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
