# Generated by Django 4.1.5 on 2023-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_alter_productdetail_name_alter_productdetail_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
