# Generated by Django 4.1.5 on 2023-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0005_alter_productdetail_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
