# Generated by Django 4.2 on 2023-06-21 12:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("phone_branch", models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Site_User",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Admin"), (1, "Manager"), (2, "Seller")], default=2
                    ),
                ),
                ("salary", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "branch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Seller.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
