# Generated by Django 4.1.5 on 2023-04-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
