# Generated by Django 4.2 on 2023-04-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="manager",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("phone_branch", models.CharField(blank=True, max_length=11)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Seller.seller",
                    ),
                ),
            ],
        ),
    ]
