# Generated by Django 4.2 on 2023-06-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site_user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Seller.branch",
            ),
        ),
    ]
