# Generated by Django 4.2 on 2023-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="due_by_days",
            field=models.PositiveIntegerField(default=14, null=True),
        ),
    ]
