# Generated by Django 4.2 on 2024-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_sitesettings_due_by_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="SiteName",
            field=models.CharField(default="No Name", max_length=250),
        ),
    ]
