# Generated by Django 4.1.5 on 2023-04-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("mario", "mario"),
                    ("Malak", "malak"),
                    ("Alabd", "Alabd"),
                    ("Sefen", "Sefen"),
                    ("Zalamoka", "Zalamoka"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Invoice.buyer",
            ),
        ),
    ]
