# Generated by Django 4.1.5 on 2023-04-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_size_remove_productdetail_size_productdetail_sizes"),
        ("Invoice", "0002_alter_cart_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Product.size",
            ),
        ),
    ]
