# Generated by Django 4.2 on 2023-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0002_alter_cart_cart_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="gender",
            field=models.CharField(
                choices=[("Man", "man"), ("Women", "man")], default="Man", max_length=10
            ),
        ),
    ]
