# Generated by Django 4.1.5 on 2023-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0003_buyer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="gender",
            field=models.CharField(
                choices=[("man", "Man"), ("women", "Women")],
                default="Man",
                max_length=10,
            ),
        ),
    ]
