# Generated by Django 4.2 on 2023-08-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0002_alter_site_user_branch"),
        ("Invoice", "0003_cart_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts_edited",
                to="Seller.site_user",
            ),
        ),
    ]
