# Generated by Django 4.1.5 on 2023-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0004_order_created_at_alter_buyer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
