# Generated by Django 4.2 on 2023-04-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0005_cart_is_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Invoice.buyer",
            ),
        ),
    ]
