# Generated by Django 4.1.5 on 2023-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice", "0006_cart_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="edit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
